[package]
name = "db"
version.workspace = true
edition.workspace = true

[lib]
name = "db"
path = "mod.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.5", features = ["v4", "serde"] }
